name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: kernel/Dockerfile
          tags: smartxworks/capch-kernel-5.15.12
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: rootfs/Dockerfile
          tags: smartxworks/capch-rootfs-1.24.0
          push: true
